#"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os$directory$\
git_branch$git_status\
$rust\
$nodejs\
$python\
$java\
$kotlin\
$fill\
$status$cmd_duration
$character
"""

[character]
error_symbol = '[âŒ](bold red)'

[os]
format = '[$symbol](white)'
disabled = false

[os.symbols]
Arch = "ïŒƒ "
Debian = "ïŒ† "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[directory]
style = "blue"
truncation_length = 0
truncate_to_repo = false
read_only = " ó°Œ¾"

[git_branch]
symbol = 'î‚  '
format = 'via [$symbol$branch]($style)'
#truncation_length = 4
#truncation_symbol = 'â€¦'
style = 'bold purple'

[git_status]
format = '([ \[ $all_status$ahead_behind\]]($style) )'
style = 'bold purple'
conflicted = '[ïª confliced=${count}](red) '
up_to_date = '[ó°˜½ up-to-date](green) '
untracked = '[ó°‹— untracked=${count}](red) '
ahead = 'ï‚ª ahead=${count}'
diverged = 'ï‚ª ahead=${ahead_count} ï‚« behind=${behind_count}'
behind = 'ï‚« behind=${count}'
stashed = '[ïŠ‹ stashed=${count}](green) '
modified = '[ó°›¿ modified=${count}](yellow) '
staged = '[ó°— staged=${count}](green) '
renamed = '[ó±¸ renamed=${count}](yellow) '
deleted = '[ó°¶ deleted=${count}](red) '

#[package]
#format = 'via [$symbol $version](208 bold)'
#symbol = "ó°— "
#disabled = false

[rust]
format = ' [$symbol Rust $version](208 bold)'
symbol = 'ğŸ¦€ '

[nodejs]
format = ' [$symbol Node.js $version](green bold)'
symbol = 'îœ˜ '

[python]
format = ' [$symbol Python $version](yellow bold)[ $virtualenv](cyan bold)'
symbol = "îˆµ "

[java]
format = ' [$symbol Java $version](208 bold)'
symbol = "î‰– "

[kotlin]
format = ' [$symbol Kotlin $version](blue bold)'
symbol = "î˜´ "

[fill]
symbol= ' '

[status]
symbol = '[âŒ](bold red)'
disabled = false

[cmd_duration]
min_time = 2
format = '[$duration](bold yellow)'
disabled = false